import Link from "next/link";
import { ArrowLeft, Package, Plus, Search } from "@/components/icons";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { formatPrice } from "@/lib/catalog";
import type { AdminProduct } from "@/types/admin-catalog";
const PAGE_SIZE = 50;
export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ busca?: string; pagina?: string }> }) {
  const { busca = "", pagina = "1" } = await searchParams; const page = Math.max(1, Number.parseInt(pagina, 10) || 1);
  const { data, error } = await (await createSupabaseServerClient()).rpc("admin_list_products_page", { search_term: busca, result_limit: PAGE_SIZE, result_offset: (page - 1) * PAGE_SIZE });
  const products = (data ?? []) as AdminProduct[]; const total = Number(products[0]?.total_count ?? 0); const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const hrefFor = (target: number) => `/admin/produtos?pagina=${target}${busca ? `&busca=${encodeURIComponent(busca)}` : ""}`;
  return <main className="admin-content"><Link href="/admin" className="back-link"><ArrowLeft size={17} /> Voltar ao início</Link><div className="admin-heading"><div><p>CATÁLOGO</p><h1>Meus produtos</h1><span className="admin-heading-note">{total} itens cadastrados</span></div><Link href="/admin/produtos/novo" className="button button-primary"><Plus />Adicionar peça</Link></div><form className="admin-search" action="/admin/produtos"><Search size={18} /><input name="busca" defaultValue={busca} placeholder="Buscar por peça, código ou fabricante" /><button className="button button-ghost">Buscar</button></form>{error ? <div className="admin-notice error">Não foi possível carregar os produtos. Tente novamente.</div> : <section className="admin-products admin-products-page"><div className="admin-section-title"><div><h2>Produtos cadastrados</h2><p>Página {Math.min(page, pages)} de {pages}</p></div></div>{products.length === 0 ? <div className="admin-empty"><Package size={38} /><strong>Nenhum produto encontrado</strong><p>Tente outro termo ou adicione uma peça.</p></div> : <div className="admin-table">{products.map((product) => <div className="admin-row" key={product.id}><span className="admin-thumb"><Package /></span><div className="admin-product-name"><strong>{product.name}</strong><small>{product.manufacturer_code || product.internal_code}{product.brand ? ` · ${product.brand}` : ""}</small></div><strong>{product.regular_price_cents ? formatPrice(product.regular_price_cents) : "Sob consulta"}</strong><span className={`status-pill ${product.publication_status}`}>{product.publication_status === "published" ? "Publicado" : product.publication_status === "draft" ? "Rascunho" : "Arquivado"}</span><span className="admin-row-date">{new Intl.DateTimeFormat("pt-BR").format(new Date(product.updated_at))}</span></div>)}</div>}<nav className="admin-pagination" aria-label="Paginação">{page > 1 && <Link href={hrefFor(page - 1)} className="button button-ghost">Anterior</Link>}<span>{page} / {pages}</span>{page < pages && <Link href={hrefFor(page + 1)} className="button button-ghost">Próxima</Link>}</nav></section>}</main>;
}
