"""Build the idempotent APM1 catalog data migration from parsed JSON."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ROWS_PATH = ROOT / "data" / "imports" / "lote-apm1" / "rows.json"
SUMMARY_PATH = ROOT / "data" / "imports" / "lote-apm1" / "summary.json"
MIGRATION_PATH = ROOT / "supabase" / "migrations" / "20260910103000_import_lote_apm1.sql"


def sql_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("'", "''")


def main() -> None:
    rows = json.loads(ROWS_PATH.read_text(encoding="utf-8"))
    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    payload = sql_json(rows)
    summary_payload = sql_json(summary)
    migration = f"""-- Generated by scripts/build_lote_apm_migration.py.
-- Imports the APM1 source as private staging rows and safe product drafts.

insert into catalog.stores (slug, display_name, whatsapp_e164)
values ('auto-pecas-martins', 'Auto Peças Martins', '5513996002719')
on conflict (slug) do update set
  display_name = excluded.display_name,
  whatsapp_e164 = excluded.whatsapp_e164;

with target_store as (
  select id from catalog.stores where slug = 'auto-pecas-martins'
), category_seed(name, slug, sort_order) as (
  values
    ('Borracha e vedação', 'borracha-e-vedacao', 10),
    ('Calhas', 'calhas', 20),
    ('Iluminação', 'iluminacao', 30),
    ('Retrovisores', 'retrovisores', 40),
    ('Molduras e grades', 'molduras-e-grades', 50),
    ('Para-barros', 'para-barros', 60)
)
insert into catalog.categories (store_id, name, slug, sort_order)
select target_store.id, category_seed.name, category_seed.slug, category_seed.sort_order
from target_store cross join category_seed
on conflict (store_id, slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

with target_store as (
  select id from catalog.stores where slug = 'auto-pecas-martins'
)
insert into catalog.import_batches (
  store_id, source_name, source_sha256, source_rows, summary, status, imported_at
)
select
  id,
  'LOTES APM1.pdf',
  '{summary['sha256']}',
  {summary['rows']},
  '{summary_payload}'::jsonb,
  'parsed',
  null
from target_store
on conflict (store_id, source_sha256) do nothing;

with payload as (
  select * from jsonb_to_recordset('{payload}'::jsonb) as source (
    source_page integer,
    source_row integer,
    category text,
    description text,
    manufacturer_code text,
    brand text,
    quantity integer,
    source_price_cents integer,
    sale_price_cents integer,
    total_cents integer,
    confidence text,
    issues text[],
    source_fingerprint text,
    internal_code text,
    slug text
  )
), context as (
  select s.id as store_id, b.id as batch_id
  from catalog.stores s
  join catalog.import_batches b on b.store_id = s.id
  where s.slug = 'auto-pecas-martins'
    and b.source_sha256 = '{summary['sha256']}'
)
insert into catalog.import_rows (
  batch_id, store_id, source_page, source_row, category_name,
  raw_description, manufacturer_code, brand, quantity,
  source_price_cents, sale_price_cents, total_cents, confidence,
  issues, source_fingerprint
)
select
  context.batch_id, context.store_id, payload.source_page, payload.source_row,
  payload.category, payload.description, payload.manufacturer_code, payload.brand,
  payload.quantity, payload.source_price_cents, payload.sale_price_cents,
  payload.total_cents, payload.confidence::catalog.import_confidence,
  coalesce(payload.issues, '{{}}'), payload.source_fingerprint
from payload cross join context
on conflict (store_id, source_fingerprint) do nothing;

with payload as (
  select * from jsonb_to_recordset('{payload}'::jsonb) as source (
    source_row integer,
    category text,
    description text,
    manufacturer_code text,
    brand text,
    sale_price_cents integer,
    internal_code text,
    slug text
  )
), target_store as (
  select id from catalog.stores where slug = 'auto-pecas-martins'
)
insert into catalog.products (
  store_id, category_id, internal_code, manufacturer_code, slug, name,
  brand, description, price_mode, regular_price_cents,
  publication_status, availability_status
)
select
  target_store.id,
  category.id,
  payload.internal_code,
  payload.manufacturer_code,
  payload.slug,
  payload.description,
  payload.brand,
  'Importado do lote APM1; aguardando revisão de aplicação, foto e preço.',
  'fixed',
  payload.sale_price_cents,
  'draft',
  'available'
from payload
cross join target_store
join catalog.categories category
  on category.store_id = target_store.id and category.name = payload.category
on conflict (store_id, internal_code) do nothing;

with target_store as (
  select id from catalog.stores where slug = 'auto-pecas-martins'
), target_batch as (
  select b.id, b.store_id
  from catalog.import_batches b
  join target_store s on s.id = b.store_id
  where b.source_sha256 = '{summary['sha256']}'
)
update catalog.import_rows row
set
  product_id = product.id,
  review_status = 'imported'
from target_batch
join catalog.products product on product.store_id = target_batch.store_id
where row.batch_id = target_batch.id
  and row.store_id = target_batch.store_id
  and product.internal_code = 'APM1-' || lpad(row.source_row::text, 4, '0');

with target_store as (
  select id from catalog.stores where slug = 'auto-pecas-martins'
)
update catalog.import_batches batch
set status = 'imported', imported_at = now()
from target_store
where batch.store_id = target_store.id
  and batch.source_sha256 = '{summary['sha256']}';
"""
    MIGRATION_PATH.write_text(migration, encoding="utf-8")
    print(f"Wrote {MIGRATION_PATH.relative_to(ROOT)} with {len(rows)} rows")


if __name__ == "__main__":
    main()
