import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { WhatsAppLink } from "@/components/whatsapp-link";
import { ArrowRight, Package } from "@/components/icons";
import { catalogProducts, formatPrice, getProductBySlug } from "@/lib/catalog";

export function generateStaticParams() { return catalogProducts.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const product = getProductBySlug((await params).slug); return product ? { title: `${product.name} ${product.code} em Jacupiranga | Auto Peças Martins`, description: `${product.application}. Consulte preço e disponibilidade na Auto Peças Martins.` } : {}; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const product = getProductBySlug(slug); if (!product) notFound(); const message = `Olá! Vi no site a peça ${product.name}, código ${product.code}, anunciada por ${formatPrice(product.priceCents)}. Meu veículo é [modelo/ano]. Gostaria de confirmar aplicação e disponibilidade.`; const schema = { "@context": "https://schema.org", "@type": "Product", name: product.name, sku: product.code, brand: product.brand ? { "@type": "Brand", name: product.brand } : undefined, description: product.description, image: product.imageSrc, offers: { "@type": "Offer", priceCurrency: "BRL", price: (product.priceCents / 100).toFixed(2), availability: "https://schema.org/InStock" } }; return <main id="conteudo"><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><section className="section product-page"><div className="container"><Link href="/catalogo" className="breadcrumb">Catálogo <ArrowRight size={15} /> {product.category}</Link><div className="product-layout"><div className={`product-large-visual ${product.imageSrc ? "has-photo" : ""}`}><span className="lot-badge">LOTE APM1</span>{product.imageSrc ? <Image src={product.imageSrc} alt={product.name} fill priority sizes="(max-width: 850px) 100vw, 50vw" /> : <><Package size={72} /><span>Imagem em validação</span><small>A foto será adicionada após conferência do código e da aplicação.</small></>}</div><article className="product-summary"><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><p className="product-application">{product.application}</p><div className="price-block"><span>Preço de referência do lote</span><strong>{formatPrice(product.priceCents)}</strong><small>Preço, estoque e aplicação sujeitos à confirmação</small></div><WhatsAppLink message={message} label="Confirmar no WhatsApp" /><dl><div><dt>Código</dt><dd>{product.code}</dd></div><div><dt>Marca</dt><dd>{product.brand ?? "Não informada"}</dd></div><div><dt>Disponibilidade</dt><dd>{product.availability}</dd></div></dl><div className="compatibility-note"><strong>Confirme antes de comprar</strong><p>{product.description} Informe também modelo, ano e motorização do seu carro.</p></div></article></div></div></section><SiteFooter /></main>; }
